spring:
  application:
    name: atores-api
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/scea
    username: postgres
    password: "1234"
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: atores
        format_sql: true

logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.hibernate.SQL: DEBUG

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
