import { test, expect } from '@playwright/test';

const BASE_URL = 'http://localhost:5173';
const TEST_EMAIL = 'gustavo.cortez@ufms.br';
const TEST_PASS = '123';

test.describe('Fluxo Completo SCEA E2E', () => {

  test('deve completar o ciclo de vida total do protocolo', async ({ page }) => {
    // 1. LOGIN
    await page.goto('/');
    await page.fill('input[id="email"]', TEST_EMAIL);
    await page.fill('input[id="senha"]', TEST_PASS);
    await page.click('button[type="submit"]');
    
    // Check if logged in (Header should show user name)
    await expect(page.getByRole('banner')).toBeVisible();

    // If we have multi-roles, ensure we are in Docente mode for these tests
    const docenteBtn = page.getByRole('banner').getByRole('button', { name: 'Ver como Docente' });
    if (await docenteBtn.isVisible()) {
        await docenteBtn.click();
    }

    // 2. SUBMIT PROTOCOL (DOCENTE FLOW)
    await page.getByRole('button', { name: 'Nova Submissão' }).click();
    
    // Step 1: Texts
    await page.fill('label:has-text("Título do Projeto") + input', 'Estudo Playwright E2E');
    await page.fill('label:has-text("Objetivo") + textarea', 'Validar todo o fluxo do sistema de forma automatizada.');
    await page.fill('label:has-text("Justificativa Científica") + textarea', 'Necessário para garantir que a integração entre microserviços está funcionando.');
    await page.fill('label:has-text("Resumo (PT)") + textarea', 'Este é um resumo gerado pelo teste automatizado do Playwright.');
    await page.fill('label:has-text("Resumo (EN)") + textarea', 'This is a summary generated by Playwright automated end-to-end testing.');
    await page.click('button:has-text("Próximo")');

    // Step 2: Dates (Avoid weekends/holidays)
    await page.fill('input[id="data-inicio"]', '2026-06-22');
    await page.fill('input[id="data-termino"]', '2026-06-30');
    await page.click('button:has-text("Próximo")');

    // Step 3: Allocation
    await page.waitForLoadState('networkidle');
    
    await page.selectOption('select[id="especie-select"]', { index: 1 });
    await page.fill('input[id="quantidade-input"]', '10');
    await page.selectOption('select[id="bioterio-select"]', { index: 1 });

    await page.click('button:has-text("Adicionar à Lista")');
    
    await expect(page.locator('table tbody tr')).toHaveCount(1);
    await page.click('button:has-text("Finalizar e Submeter")');

    // Verify it appeared in the list
    await expect(page.locator('tr').filter({ hasText: 'Estudo Playwright E2E' }).first()).toBeVisible();
    
    console.log('Protocol submitted successfully via UI');
  });

  test('deve falhar o login com credenciais inválidas', async ({ page }) => {
    await page.goto(BASE_URL);
    await page.fill('input[id="email"]', 'errado@scea.local');
    await page.fill('input[id="senha"]', 'senha-errada');
    await page.click('button[type="submit"]');

    await expect(page.getByRole('alert')).toBeVisible();
    await expect(page.getByText('Usuário ou senha inválidos')).toBeVisible();
  });
});
